version: 0.0
os: linux
files:
  - source: /scripts/start_container.sh
    destination: /usr/local/bin/
hooks:
  ApplicationStart:
    - location: start_container.sh
      timeout: 300
      runas: root
